name: "Trigger FrontEnd Pipeline"

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**' 


jobs:
  deploy:
    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@vX.X.X
        with:
          aws-region: "eu-west-1"
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          pipeline-name: "eadesign-pipeline-fe"